/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_oa_websocket_jni_ArServerDetectorJni */

#ifndef _Included_org_oa_websocket_jni_ArServerDetectorJni
#define _Included_org_oa_websocket_jni_ArServerDetectorJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_oa_websocket_jni_ArServerDetectorJni
 * Method:    arServerDetectorJni
 * Signature: (Lorg/oa/websocket/model/JniParametrs;)V
 */
JNIEXPORT void JNICALL Java_org_oa_websocket_jni_ArServerDetectorJni_arServerDetectorJni
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
