/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_oa_websocket_jni_ArServerDetectorJni */

#ifndef _Included_org_oa_websocket_jni_ArServerDetectorJni
#define _Included_org_oa_websocket_jni_ArServerDetectorJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_org_oa_websocket_jni_ArServerDetector_initSession
  (JNIEnv *, jclass, jobject, jstring,jstring,jintArray,jobjectArray);

  JNIEXPORT jint JNICALL Java_org_oa_websocket_jni_ArServerDetector_detect
  (JNIEnv *, jclass, jobject, jint,jbyteArray);


  JNIEXPORT void JNICALL Java_org_oa_websocket_jni_ArServerDetector_closeSession
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
