/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArServerDetectorJni */

#ifndef _Included_ArServerDetectorJni
#define _Included_ArServerDetectorJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArServerDetectorJni
 * Method:    initSession
 * Signature: (Ljava/lang/String;Ljava/lang/String;[I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ArServerDetectorJni_initSession
  (JNIEnv *, jobject, jstring, jstring, jintArray, jobjectArray);

/*
 * Class:     ArServerDetectorJni
 * Method:    detect
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_ArServerDetectorJni_detect
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     ArServerDetectorJni
 * Method:    closeSession
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ArServerDetectorJni_closeSession
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
